import type {
  CategoryId,
  InvitationTemplate,
  TemplateField,
  TemplateTheme,
} from "./types";

export const PRICE = 19_999;

export const CATEGORIES: {
  id: CategoryId;
  slug: string;
  title: string;
  description: string;
}[] = [
  {
    id: "toy",
    slug: "toy",
    title: "To'y taklifnomasi",
    description: "Nikoh marosimi uchun cinematic va romantik taklifnomalar.",
  },
  {
    id: "taklifnoma",
    slug: "taklifnoma",
    title: "Taklifnoma",
    description: "Rasmiy tadbir, oilaviy kecha va tantanalar uchun.",
  },
  {
    id: "tabriknoma",
    slug: "tabriknoma",
    title: "Tabriknoma",
    description: "Yaqinlaringizga yuboriladigan nafis raqamli tabrik.",
  },
  {
    id: "uchrashuv",
    slug: "uchrashuv",
    title: "Uchrashuv taklifnomasi",
    description: "Kecha, kechki ovqat yoki maxsus uchrashuv chaqiruvi.",
  },
  {
    id: "video-tabrik",
    slug: "video-tabrik",
    title: "Videolik tabriknoma",
    description: "Musiqa va kadrlar bilan jonli tabrik syujeti.",
  },
  {
    id: "video-taklif",
    slug: "video-taklif",
    title: "Videolik taklifnoma",
    description: "To'y yoki tadbir uchun kino uslubidagi taklif.",
  },
  {
    id: "tugilgan-kun",
    slug: "tugilgan-kun",
    title: "Tug'ilgan kun",
    description: "Yosh to'yishi va tug'ilgan kun kechalari uchun.",
  },
];

const WEDDING_FIELDS: TemplateField[] = [
  { key: "groom", label: "Kuyov ismi", type: "text", required: true, placeholder: "Sardor" },
  { key: "bride", label: "Kelin ismi", type: "text", required: true, placeholder: "Madina" },
  { key: "greeting", label: "Taklif matni", type: "textarea", required: true, placeholder: "Sizni nikoh to'yimizga marhamat qilamiz..." },
  { key: "date", label: "Sana", type: "date", required: true },
  { key: "time", label: "Vaqt", type: "time", required: true },
  { key: "venue", label: "Maskan", type: "text", required: true, placeholder: "Hilton Garden Inn" },
  { key: "address", label: "Manzil", type: "text", required: true, placeholder: "Toshkent, Amir Temur ko'chasi" },
  { key: "mapUrl", label: "Xarita havolasi", type: "map", placeholder: "https://maps.google.com/..." },
  { key: "phone", label: "Telefon", type: "phone", placeholder: "+998 90 123 45 67" },
  { key: "parentsGroom", label: "Kuyov ota-onasi", type: "text", placeholder: "Akmal va Dilbar aka-opalar" },
  { key: "parentsBride", label: "Kelin ota-onasi", type: "text", placeholder: "Jahongir va Nodira aka-opalar" },
  { key: "coverPhoto", label: "Asosiy foto", type: "image" },
  { key: "gallery", label: "Galereya", type: "images", max: 6 },
  { key: "music", label: "Fon musiqasi", type: "music" },
  { key: "countdownEnabled", label: "Hisoblagich", type: "boolean" },
  { key: "rsvpEnabled", label: "RSVP formasi", type: "boolean" },
];

const GREETING_FIELDS: TemplateField[] = [
  { key: "sender", label: "Yuboruvchi", type: "text", required: true, placeholder: "Sardor" },
  { key: "recipient", label: "Qabul qiluvchi", type: "text", required: true, placeholder: "Madina" },
  { key: "message", label: "Tabrik matni", type: "textarea", required: true },
  { key: "date", label: "Sana", type: "date" },
  { key: "coverPhoto", label: "Foto", type: "image" },
  { key: "music", label: "Fon musiqasi", type: "music" },
];

const MEETING_FIELDS: TemplateField[] = [
  { key: "title", label: "Uchrashuv nomi", type: "text", required: true, placeholder: "Kechki suhbat" },
  { key: "host", label: "Mezbon", type: "text", required: true, placeholder: "Sardor" },
  { key: "greeting", label: "Taklif matni", type: "textarea", required: true },
  { key: "date", label: "Sana", type: "date", required: true },
  { key: "time", label: "Vaqt", type: "time", required: true },
  { key: "venue", label: "Joy", type: "text", required: true },
  { key: "address", label: "Manzil", type: "text" },
  { key: "mapUrl", label: "Xarita havolasi", type: "map" },
  { key: "phone", label: "Aloqa", type: "phone" },
  { key: "coverPhoto", label: "Foto", type: "image" },
  { key: "music", label: "Fon musiqasi", type: "music" },
];

const BIRTHDAY_FIELDS: TemplateField[] = [
  { key: "honoree", label: "Tug'ilgan kun egasi", type: "text", required: true, placeholder: "Madina" },
  { key: "age", label: "Yosh", type: "number", required: true, placeholder: "25" },
  { key: "host", label: "Mezbon", type: "text", placeholder: "Oilasi" },
  { key: "greeting", label: "Taklif matni", type: "textarea", required: true },
  { key: "date", label: "Sana", type: "date", required: true },
  { key: "time", label: "Vaqt", type: "time", required: true },
  { key: "venue", label: "Joy", type: "text", required: true },
  { key: "address", label: "Manzil", type: "text" },
  { key: "phone", label: "Telefon", type: "phone" },
  { key: "coverPhoto", label: "Asosiy foto", type: "image" },
  { key: "gallery", label: "Galereya", type: "images", max: 6 },
  { key: "music", label: "Fon musiqasi", type: "music" },
  { key: "rsvpEnabled", label: "RSVP formasi", type: "boolean" },
];

const VIDEO_GREETING_FIELDS: TemplateField[] = [
  { key: "title", label: "Sarlavha", type: "text", required: true, placeholder: "Tabrik" },
  { key: "subtitle", label: "Qisqa matn", type: "text", placeholder: "Siz uchun" },
  { key: "sender", label: "Yuboruvchi", type: "text", required: true },
  { key: "recipient", label: "Qabul qiluvchi", type: "text", required: true },
  { key: "message", label: "Asosiy tabrik", type: "textarea", required: true },
  { key: "slides", label: "Kadrlar", type: "images", required: true, max: 8 },
  { key: "captions", label: "Kadr matnlari", type: "textarea", help: "Har bir qator — alohida kadr matni." },
  { key: "music", label: "Musiqa", type: "music" },
];

const VIDEO_WEDDING_FIELDS: TemplateField[] = [
  { key: "groom", label: "Kuyov ismi", type: "text", required: true },
  { key: "bride", label: "Kelin ismi", type: "text", required: true },
  { key: "greeting", label: "Taklif matni", type: "textarea", required: true },
  { key: "date", label: "Sana", type: "date", required: true },
  { key: "time", label: "Vaqt", type: "time" },
  { key: "venue", label: "Maskan", type: "text", required: true },
  { key: "slides", label: "Video kadrlar", type: "images", required: true, max: 8 },
  { key: "captions", label: "Kadr matnlari", type: "textarea", help: "Har bir qator — alohida kadr matni." },
  { key: "music", label: "Musiqa", type: "music" },
  { key: "phone", label: "Telefon", type: "phone" },
];

const DEMO_WEDDING = {
  groom: "Sardor",
  bride: "Madina",
  greeting:
    "Qadrli mehmonlar, sizni hayotimizning eng nurlı kuniga — nikoh to'yimizga taklif etamiz. Marhamat qiling, biz bilan shu lahzani baham ko'ring.",
  date: "2026-08-22",
  time: "18:00",
  venue: "Hilton Garden Inn",
  address: "Toshkent, Amir Temur shoh ko'chasi, 24",
  mapUrl: "https://maps.google.com/?q=Toshkent+Hilton+Garden+Inn",
  phone: "+998 90 123 45 67",
  parentsGroom: "Akmal va Dilbar aka-opalar",
  parentsBride: "Jahongir va Nodira aka-opalar",
  music: "ipak-tuni",
  countdownEnabled: true,
  rsvpEnabled: true,
};

function theme(partial: TemplateTheme): TemplateTheme {
  return partial;
}

export const TEMPLATES: InvitationTemplate[] = [
  {
    id: "guldasta",
    category: "toy",
    title: "Guldasta",
    tagline: "Gul va ipak nafasidagi nikoh taklifnomasi",
    price: PRICE,
    previewImage: "/images/templates/guldasta/cover.jpg",
    background: "/images/templates/guldasta/background.jpg",
    gallery: [
      "/images/templates/guldasta/gallery-1.jpg",
      "/images/templates/guldasta/gallery-2.jpg",
      "/images/hero/roses.jpg",
    ],
    fonts: { display: "Cormorant Garamond", body: "Outfit", script: "Great Vibes" },
    fields: WEDDING_FIELDS,
    sections: ["cover", "names", "verse", "photo", "datetime", "event", "parents", "gallery", "location", "countdown", "rsvp", "footer"],
    theme: theme({
      style: "floral",
      paper: "#F7F1E8",
      ink: "#3A2A22",
      muted: "#7A6A62",
      accent: "#C99A9A",
      gold: "#B8956A",
      overlay: "rgba(247,241,232,0.04)",
    }),
    animations: ["fade-up", "petal"],
    isVideo: false,
    demo: { ...DEMO_WEDDING, coverPhoto: "/images/templates/guldasta/cover.jpg", gallery: ["/images/templates/guldasta/gallery-1.jpg", "/images/templates/guldasta/gallery-2.jpg"] },
  },
  {
    id: "shohona",
    category: "toy",
    title: "Shohona",
    tagline: "Kechki zal va oltin yorug'likdagi cinematic to'y",
    price: PRICE,
    previewImage: "/images/templates/shohona/cover.jpg",
    background: "/images/templates/shohona/background.jpg",
    gallery: [
      "/images/templates/shohona/gallery-1.jpg",
      "/images/templates/shohona/gallery-2.jpg",
      "/images/hero/venue.jpg",
    ],
    fonts: { display: "Cormorant Garamond", body: "Outfit", script: "Great Vibes" },
    fields: WEDDING_FIELDS,
    sections: ["cover", "names", "verse", "datetime", "event", "photo", "parents", "gallery", "location", "countdown", "rsvp", "footer"],
    theme: theme({
      style: "cinematic",
      paper: "#1A080C",
      ink: "#F3E6D8",
      muted: "#D4C4A8",
      accent: "#C9A06A",
      gold: "#E0D0B0",
      overlay: "rgba(12,4,8,0.08)",
    }),
    animations: ["mask-reveal", "gold-line"],
    isVideo: false,
    demo: { ...DEMO_WEDDING, venue: "Navoiy teatri", coverPhoto: "/images/templates/shohona/cover.jpg", gallery: ["/images/templates/shohona/gallery-1.jpg", "/images/hero/venue.jpg"] },
  },
  {
    id: "ipak-xat",
    category: "taklifnoma",
    title: "Ipak xat",
    tagline: "Ipak to'qima va yumshoq yorug'likdagi rasmiy taklif",
    price: PRICE,
    previewImage: "/images/templates/ipak-xat/cover.jpg",
    background: "/images/templates/ipak-xat/background.jpg",
    gallery: ["/images/templates/ipak-xat/gallery-1.jpg", "/images/templates/ipak-xat/gallery-2.jpg"],
    fonts: { display: "Cormorant Garamond", body: "Outfit", script: "Great Vibes" },
    fields: [
      { key: "title", label: "Tadbir nomi", type: "text", required: true, placeholder: "Oilaviy kecha" },
      { key: "host", label: "Mezbon", type: "text", required: true },
      { key: "greeting", label: "Taklif matni", type: "textarea", required: true },
      { key: "date", label: "Sana", type: "date", required: true },
      { key: "time", label: "Vaqt", type: "time", required: true },
      { key: "venue", label: "Maskan", type: "text", required: true },
      { key: "address", label: "Manzil", type: "text" },
      { key: "mapUrl", label: "Xarita", type: "map" },
      { key: "phone", label: "Telefon", type: "phone" },
      { key: "coverPhoto", label: "Foto", type: "image" },
      { key: "music", label: "Musiqa", type: "music" },
      { key: "rsvpEnabled", label: "RSVP", type: "boolean" },
    ],
    sections: ["cover", "names", "message", "datetime", "event", "location", "rsvp", "footer"],
    theme: theme({
      style: "silk",
      paper: "#12102A",
      ink: "#F3E6D8",
      muted: "#C4B8D4",
      accent: "#9AA0C8",
      gold: "#D4C4A8",
      overlay: "rgba(10,8,28,0.06)",
    }),
    animations: ["silk-fade"],
    isVideo: false,
    demo: {
      title: "Oilaviy kecha",
      host: "Sardor va Madina",
      greeting: "Qadrli yaqinlar, sizni ipak kechamizga marhamat qilamiz. Suhbat, musiqa va iliqlik kutadi.",
      date: "2026-09-12",
      time: "19:30",
      venue: "Private salon",
      address: "Toshkent, Yakkasaroy",
      phone: "+998 90 123 45 67",
      music: "guliston",
      rsvpEnabled: true,
      coverPhoto: "/images/templates/ipak-xat/cover.jpg",
    },
  },
  {
    id: "yulduz-tabrik",
    category: "tabriknoma",
    title: "Yulduz tabrik",
    tagline: "Suv bo'yoqli, yumshoq va shaxsiy tabriknoma",
    price: PRICE,
    previewImage: "/images/templates/yulduz-tabrik/cover.jpg",
    background: "/images/templates/yulduz-tabrik/background.jpg",
    gallery: ["/images/templates/yulduz-tabrik/gallery-1.jpg", "/images/templates/yulduz-tabrik/gallery-2.jpg"],
    fonts: { display: "Cormorant Garamond", body: "Outfit", script: "Great Vibes" },
    fields: GREETING_FIELDS,
    sections: ["cover", "names", "message", "photo", "footer"],
    theme: theme({
      style: "watercolor",
      paper: "#0B1224",
      ink: "#F7F1E8",
      muted: "#C4B8D0",
      accent: "#A8B4E0",
      gold: "#E8DCC0",
      overlay: "rgba(8,10,28,0.08)",
    }),
    animations: ["wash"],
    isVideo: false,
    demo: {
      sender: "Sardor",
      recipient: "Madina",
      message: "Yuragimdagi eng iliqlik — senga. Har tonging yulduzdek yorug', har kechang sokin va baxtli bo'lsin.",
      date: "2026-08-22",
      music: "yulduzlar",
      coverPhoto: "/images/templates/yulduz-tabrik/cover.jpg",
    },
  },
  {
    id: "kechki-uchrashuv",
    category: "uchrashuv",
    title: "Kechki bog'",
    tagline: "Romantik bog' manzarasidagi uchrashuv chaqiruvi",
    price: PRICE,
    previewImage: "/images/templates/kechki-uchrashuv/cover.jpg",
    background: "/images/templates/kechki-uchrashuv/background.jpg",
    gallery: ["/images/templates/kechki-uchrashuv/gallery-1.jpg", "/images/hero/garden.jpg"],
    fonts: { display: "Cormorant Garamond", body: "Outfit", script: "Great Vibes" },
    fields: MEETING_FIELDS,
    sections: ["cover", "names", "message", "datetime", "event", "location", "footer"],
    theme: theme({
      style: "garden",
      paper: "#F4EDE3",
      ink: "#2A3A28",
      muted: "#5C6B58",
      accent: "#6B8A62",
      gold: "#8A7A4A",
      overlay: "rgba(244,237,227,0.04)",
    }),
    animations: ["leaf"],
    isVideo: false,
    demo: {
      title: "Kechki suhbat",
      host: "Sardor",
      greeting: "Sizni kechki bog'da, sham chiroqlar ostida suhbatga taklif etaman. Iltimos, shu kechani bizga bag'ishlang.",
      date: "2026-08-29",
      time: "20:00",
      venue: "Botanika bog'i terrasi",
      address: "Toshkent, Yunusobod",
      phone: "+998 90 123 45 67",
      music: "sokin-yurak",
      coverPhoto: "/images/templates/kechki-uchrashuv/cover.jpg",
    },
  },
  {
    id: "video-yoruglik",
    category: "video-tabrik",
    title: "Yorug'lik",
    tagline: "Kadrlar, musiqa va matn bilan jonli tabrik",
    price: PRICE,
    previewImage: "/images/templates/video-yoruglik/cover.jpg",
    background: "/images/templates/video-yoruglik/background.jpg",
    gallery: [
      "/images/templates/video-yoruglik/cover.jpg",
      "/images/templates/video-yoruglik/gallery-1.jpg",
      "/images/templates/video-yoruglik/gallery-2.jpg",
      "/images/templates/yulduz-tabrik/cover.jpg",
    ],
    fonts: { display: "Cormorant Garamond", body: "Outfit", script: "Great Vibes" },
    fields: VIDEO_GREETING_FIELDS,
    sections: ["video-sequence", "message", "footer"],
    theme: theme({
      style: "video",
      paper: "#0B1224",
      ink: "#F7F1E8",
      muted: "#D4C4A8",
      accent: "#C99A9A",
      gold: "#E8DCC0",
      overlay: "rgba(8,10,28,0.2)",
    }),
    animations: ["kenburns", "caption"],
    isVideo: true,
    demo: {
      title: "Senga",
      subtitle: "Yurakdan",
      sender: "Sardor",
      recipient: "Madina",
      message: "Har bir kadr — sening tabassuming. Bu kichik film faqat senga.",
      slides: [
        "/images/templates/video-yoruglik/cover.jpg",
        "/images/templates/video-yoruglik/gallery-1.jpg",
        "/images/templates/yulduz-tabrik/cover.jpg",
        "/images/templates/video-yoruglik/gallery-2.jpg",
      ],
      captions: "Birinchi nazar\nBirga o'tgan kunlar\nYulduzli kechalar\nVa yangi ertalab",
      music: "yulduzlar",
    },
  },
  {
    id: "video-nikoh",
    category: "video-taklif",
    title: "Nikoh kinosi",
    tagline: "To'y taklifnomasi — kino treyler uslubida",
    price: PRICE,
    previewImage: "/images/templates/video-nikoh/cover.jpg",
    background: "/images/templates/video-nikoh/background.jpg",
    gallery: [
      "/images/templates/video-nikoh/cover.jpg",
      "/images/templates/video-nikoh/gallery-1.jpg",
      "/images/templates/shohona/cover.jpg",
      "/images/templates/video-nikoh/gallery-2.jpg",
    ],
    fonts: { display: "Cormorant Garamond", body: "Outfit", script: "Great Vibes" },
    fields: VIDEO_WEDDING_FIELDS,
    sections: ["video-sequence", "names", "datetime", "event", "footer"],
    theme: theme({
      style: "video",
      paper: "#16080C",
      ink: "#F7F1E8",
      muted: "#D4C4A8",
      accent: "#C99A9A",
      gold: "#E0D0B0",
      overlay: "rgba(10,4,8,0.22)",
    }),
    animations: ["kenburns", "title-reveal"],
    isVideo: true,
    demo: {
      ...DEMO_WEDDING,
      slides: [
        "/images/templates/video-nikoh/cover.jpg",
        "/images/templates/shohona/cover.jpg",
        "/images/templates/video-nikoh/gallery-1.jpg",
        "/images/templates/video-nikoh/gallery-2.jpg",
      ],
      captions: "Sardor va Madina\n22 Avgust, 2026\nNikoh to'yi\nSizni kutamiz",
      coverPhoto: "/images/templates/video-nikoh/cover.jpg",
    },
  },
  {
    id: "qutlug-yosh",
    category: "tugilgan-kun",
    title: "Qutlug' yosh",
    tagline: "Milliy naqsh bilan tug'ilgan kun taklifnomasi",
    price: PRICE,
    previewImage: "/images/templates/qutlug-yosh/cover.jpg",
    background: "/images/templates/qutlug-yosh/background.jpg",
    gallery: ["/images/templates/qutlug-yosh/gallery-1.jpg", "/images/templates/qutlug-yosh/gallery-2.jpg"],
    fonts: { display: "Cormorant Garamond", body: "Outfit", script: "Great Vibes" },
    fields: BIRTHDAY_FIELDS,
    sections: ["cover", "names", "age", "message", "datetime", "event", "gallery", "rsvp", "footer"],
    theme: theme({
      style: "ornament",
      paper: "#2A1810",
      ink: "#F7F1E8",
      muted: "#D4C4A8",
      accent: "#C4A574",
      gold: "#E8D5A8",
      overlay: "rgba(20,10,6,0.1)",
    }),
    animations: ["star-in"],
    isVideo: false,
    demo: {
      honoree: "Madina",
      age: "25",
      host: "Oilasi",
      greeting: "Qadrli do'stlar, Madinaning 25 yoshini birga nishonlashga marhamat qiling. Kecha iliqlik va kulguga to'la bo'ladi.",
      date: "2026-10-03",
      time: "18:30",
      venue: "Private hall",
      address: "Toshkent, Chilonzor",
      phone: "+998 90 123 45 67",
      music: "guliston",
      rsvpEnabled: true,
      coverPhoto: "/images/templates/qutlug-yosh/cover.jpg",
      gallery: ["/images/templates/qutlug-yosh/gallery-1.jpg", "/images/templates/qutlug-yosh/gallery-2.jpg"],
    },
  },
  {
    id: "naqsh",
    category: "taklifnoma",
    title: "Naqsh",
    tagline: "O'zbek girih naqshlari asosidagi tantanali taklif",
    price: PRICE,
    previewImage: "/images/templates/naqsh/cover.jpg",
    background: "/images/templates/naqsh/background.jpg",
    gallery: ["/images/templates/naqsh/gallery-1.jpg", "/images/textures/ornament.jpg"],
    fonts: { display: "Cormorant Garamond", body: "Outfit", script: "Great Vibes" },
    fields: [
      { key: "title", label: "Tantanani nomi", type: "text", required: true, placeholder: "Sunnat to'yi" },
      { key: "host", label: "Mezbon oila", type: "text", required: true },
      { key: "greeting", label: "Taklif matni", type: "textarea", required: true },
      { key: "date", label: "Sana", type: "date", required: true },
      { key: "time", label: "Vaqt", type: "time", required: true },
      { key: "venue", label: "Maskan", type: "text", required: true },
      { key: "address", label: "Manzil", type: "text" },
      { key: "mapUrl", label: "Xarita", type: "map" },
      { key: "phone", label: "Telefon", type: "phone" },
      { key: "coverPhoto", label: "Foto", type: "image" },
      { key: "music", label: "Musiqa", type: "music" },
      { key: "rsvpEnabled", label: "RSVP", type: "boolean" },
    ],
    sections: ["cover", "names", "message", "datetime", "event", "location", "rsvp", "footer"],
    theme: theme({
      style: "ornament",
      paper: "#0C1A22",
      ink: "#F7F1E8",
      muted: "#C8D4C0",
      accent: "#6A8A6A",
      gold: "#D4C4A8",
      overlay: "rgba(8,16,18,0.18)",
    }),
    animations: ["medallion"],
    isVideo: false,
    demo: {
      title: "Sunnat to'yi",
      host: "Karimovlar oilasi",
      greeting: "Qadrli qarindosh va do'stlar, farzandimizning sunnat to'yiga marhamat qilamiz. Yuzingiz kulsun, dasturxonimiz baraka topsin.",
      date: "2026-09-20",
      time: "17:00",
      venue: "To'yxona Navro'z",
      address: "Samarqand, Registon yo'li",
      phone: "+998 91 234 56 78",
      music: "ipak-tuni",
      rsvpEnabled: true,
      coverPhoto: "/images/templates/naqsh/cover.jpg",
    },
  },
  {
    id: "marvarid",
    category: "tabriknoma",
    title: "Marvarid",
    tagline: "Damask naqsh va marvarid yorug'likdagi tabrik",
    price: PRICE,
    previewImage: "/images/templates/marvarid/cover.jpg",
    background: "/images/templates/marvarid/background.jpg",
    gallery: ["/images/templates/marvarid/gallery-1.jpg", "/images/textures/damask.jpg"],
    fonts: { display: "Cormorant Garamond", body: "Outfit", script: "Great Vibes" },
    fields: GREETING_FIELDS,
    sections: ["cover", "names", "message", "photo", "footer"],
    theme: theme({
      style: "damask",
      paper: "#2A1810",
      ink: "#F7F1E8",
      muted: "#D4C4A8",
      accent: "#C4A574",
      gold: "#E8D5A8",
      overlay: "rgba(20,10,6,0.1)",
    }),
    animations: ["foil"],
    isVideo: false,
    demo: {
      sender: "Madina",
      recipient: "Onajon",
      message: "Sizning mehribonligingiz — uyimizning marvaridi. Shu kichik tabrik bilan qalbimdagi minnatdorchilikni aytaman.",
      date: "2026-03-08",
      music: "sokin-yurak",
      coverPhoto: "/images/templates/marvarid/cover.jpg",
    },
  },
];

export function getTemplate(id: string): InvitationTemplate | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export function templatesByCategory(category: CategoryId): InvitationTemplate[] {
  return TEMPLATES.filter((t) => t.category === category);
}

export function getCategory(slug: string) {
  return CATEGORIES.find((c) => c.slug === slug || c.id === slug);
}

export function invitationTitle(template: InvitationTemplate, data: InvitationTemplate["demo"]): string {
  if (typeof data.groom === "string" && typeof data.bride === "string") {
    return `${data.groom} va ${data.bride}`;
  }
  if (typeof data.honoree === "string") return data.honoree;
  if (typeof data.title === "string") return data.title;
  if (typeof data.recipient === "string") return data.recipient;
  return template.title;
}
