/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BoglanishRouteImport } from './routes/boglanish'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaxfiylikRouteImport } from './routes/maxfiylik'
import { Route as MeningTaklifnomalarimRouteImport } from './routes/mening-taklifnomalarim'
import { Route as NarxlarRouteImport } from './routes/narxlar'
import { Route as QandayIshlaydiRouteImport } from './routes/qanday-ishlaydi'
import { Route as ShartlarRouteImport } from './routes/shartlar'
import { Route as CreateTemplateIdRouteImport } from './routes/create/$templateId'
import { Route as DizaynSlugRouteImport } from './routes/dizayn/$slug'
import { Route as InvitationIdRouteImport } from './routes/invitation/$id'
import { Route as PreviewIdRouteImport } from './routes/preview/$id'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TemplatesCategoryRouteImport } from './routes/templates/$category'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BoglanishRoute = BoglanishRouteImport.update({
  id: '/boglanish',
  path: '/boglanish',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaxfiylikRoute = MaxfiylikRouteImport.update({
  id: '/maxfiylik',
  path: '/maxfiylik',
  getParentRoute: () => rootRouteImport,
} as any)
const MeningTaklifnomalarimRoute = MeningTaklifnomalarimRouteImport.update({
  id: '/mening-taklifnomalarim',
  path: '/mening-taklifnomalarim',
  getParentRoute: () => rootRouteImport,
} as any)
const NarxlarRoute = NarxlarRouteImport.update({
  id: '/narxlar',
  path: '/narxlar',
  getParentRoute: () => rootRouteImport,
} as any)
const QandayIshlaydiRoute = QandayIshlaydiRouteImport.update({
  id: '/qanday-ishlaydi',
  path: '/qanday-ishlaydi',
  getParentRoute: () => rootRouteImport,
} as any)
const ShartlarRoute = ShartlarRouteImport.update({
  id: '/shartlar',
  path: '/shartlar',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTemplateIdRoute = CreateTemplateIdRouteImport.update({
  id: '/create/$templateId',
  path: '/create/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const DizaynSlugRoute = DizaynSlugRouteImport.update({
  id: '/dizayn/$slug',
  path: '/dizayn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationIdRoute = InvitationIdRouteImport.update({
  id: '/invitation/$id',
  path: '/invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIdRoute = PreviewIdRouteImport.update({
  id: '/preview/$id',
  path: '/preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesCategoryRoute = TemplatesCategoryRouteImport.update({
  id: '/templates/$category',
  path: '/templates/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/boglanish': typeof BoglanishRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/maxfiylik': typeof MaxfiylikRoute
  '/mening-taklifnomalarim': typeof MeningTaklifnomalarimRoute
  '/narxlar': typeof NarxlarRoute
  '/qanday-ishlaydi': typeof QandayIshlaydiRoute
  '/shartlar': typeof ShartlarRoute
  '/create/$templateId': typeof CreateTemplateIdRoute
  '/dizayn/$slug': typeof DizaynSlugRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/preview/$id': typeof PreviewIdRoute
  '/templates/$category': typeof TemplatesCategoryRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/boglanish': typeof BoglanishRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/maxfiylik': typeof MaxfiylikRoute
  '/mening-taklifnomalarim': typeof MeningTaklifnomalarimRoute
  '/narxlar': typeof NarxlarRoute
  '/qanday-ishlaydi': typeof QandayIshlaydiRoute
  '/shartlar': typeof ShartlarRoute
  '/create/$templateId': typeof CreateTemplateIdRoute
  '/dizayn/$slug': typeof DizaynSlugRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/preview/$id': typeof PreviewIdRoute
  '/templates/$category': typeof TemplatesCategoryRoute
  '/templates': typeof TemplatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/boglanish': typeof BoglanishRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/maxfiylik': typeof MaxfiylikRoute
  '/mening-taklifnomalarim': typeof MeningTaklifnomalarimRoute
  '/narxlar': typeof NarxlarRoute
  '/qanday-ishlaydi': typeof QandayIshlaydiRoute
  '/shartlar': typeof ShartlarRoute
  '/create/$templateId': typeof CreateTemplateIdRoute
  '/dizayn/$slug': typeof DizaynSlugRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/preview/$id': typeof PreviewIdRoute
  '/templates/$category': typeof TemplatesCategoryRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/boglanish'
    | '/faq'
    | '/login'
    | '/maxfiylik'
    | '/mening-taklifnomalarim'
    | '/narxlar'
    | '/qanday-ishlaydi'
    | '/shartlar'
    | '/create/$templateId'
    | '/dizayn/$slug'
    | '/invitation/$id'
    | '/preview/$id'
    | '/templates/$category'
    | '/templates/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/boglanish'
    | '/faq'
    | '/login'
    | '/maxfiylik'
    | '/mening-taklifnomalarim'
    | '/narxlar'
    | '/qanday-ishlaydi'
    | '/shartlar'
    | '/create/$templateId'
    | '/dizayn/$slug'
    | '/invitation/$id'
    | '/preview/$id'
    | '/templates/$category'
    | '/templates'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/boglanish'
    | '/faq'
    | '/login'
    | '/maxfiylik'
    | '/mening-taklifnomalarim'
    | '/narxlar'
    | '/qanday-ishlaydi'
    | '/shartlar'
    | '/create/$templateId'
    | '/dizayn/$slug'
    | '/invitation/$id'
    | '/preview/$id'
    | '/templates/$category'
    | '/templates/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BoglanishRoute: typeof BoglanishRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  MaxfiylikRoute: typeof MaxfiylikRoute
  MeningTaklifnomalarimRoute: typeof MeningTaklifnomalarimRoute
  NarxlarRoute: typeof NarxlarRoute
  QandayIshlaydiRoute: typeof QandayIshlaydiRoute
  ShartlarRoute: typeof ShartlarRoute
  CreateTemplateIdRoute: typeof CreateTemplateIdRoute
  DizaynSlugRoute: typeof DizaynSlugRoute
  InvitationIdRoute: typeof InvitationIdRoute
  PreviewIdRoute: typeof PreviewIdRoute
  TemplatesCategoryRoute: typeof TemplatesCategoryRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boglanish': {
      id: '/boglanish'
      path: '/boglanish'
      fullPath: '/boglanish'
      preLoaderRoute: typeof BoglanishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maxfiylik': {
      id: '/maxfiylik'
      path: '/maxfiylik'
      fullPath: '/maxfiylik'
      preLoaderRoute: typeof MaxfiylikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mening-taklifnomalarim': {
      id: '/mening-taklifnomalarim'
      path: '/mening-taklifnomalarim'
      fullPath: '/mening-taklifnomalarim'
      preLoaderRoute: typeof MeningTaklifnomalarimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narxlar': {
      id: '/narxlar'
      path: '/narxlar'
      fullPath: '/narxlar'
      preLoaderRoute: typeof NarxlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qanday-ishlaydi': {
      id: '/qanday-ishlaydi'
      path: '/qanday-ishlaydi'
      fullPath: '/qanday-ishlaydi'
      preLoaderRoute: typeof QandayIshlaydiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shartlar': {
      id: '/shartlar'
      path: '/shartlar'
      fullPath: '/shartlar'
      preLoaderRoute: typeof ShartlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$templateId': {
      id: '/create/$templateId'
      path: '/create/$templateId'
      fullPath: '/create/$templateId'
      preLoaderRoute: typeof CreateTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dizayn/$slug': {
      id: '/dizayn/$slug'
      path: '/dizayn/$slug'
      fullPath: '/dizayn/$slug'
      preLoaderRoute: typeof DizaynSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$id': {
      id: '/invitation/$id'
      path: '/invitation/$id'
      fullPath: '/invitation/$id'
      preLoaderRoute: typeof InvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$id': {
      id: '/preview/$id'
      path: '/preview/$id'
      fullPath: '/preview/$id'
      preLoaderRoute: typeof PreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$category': {
      id: '/templates/$category'
      path: '/templates/$category'
      fullPath: '/templates/$category'
      preLoaderRoute: typeof TemplatesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BoglanishRoute: BoglanishRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  MaxfiylikRoute: MaxfiylikRoute,
  MeningTaklifnomalarimRoute: MeningTaklifnomalarimRoute,
  NarxlarRoute: NarxlarRoute,
  QandayIshlaydiRoute: QandayIshlaydiRoute,
  ShartlarRoute: ShartlarRoute,
  CreateTemplateIdRoute: CreateTemplateIdRoute,
  DizaynSlugRoute: DizaynSlugRoute,
  InvitationIdRoute: InvitationIdRoute,
  PreviewIdRoute: PreviewIdRoute,
  TemplatesCategoryRoute: TemplatesCategoryRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
